# Generated by Django 3.0.7 on 2020-06-20 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100, verbose_name='ФИО врача')),
                ('doctor_schedule', models.CharField(max_length=200, verbose_name='График работы')),
                ('doctor_description', models.TextField(verbose_name='Дополнительная информация')),
                ('doctor_image', models.ImageField(upload_to='doctors/', verbose_name='Изображение врача')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=300, verbose_name='Название препарата')),
                ('quanity', models.PositiveSmallIntegerField(default=0, verbose_name='Количетво')),
                ('checklist', models.CharField(max_length=4, verbose_name='список')),
                ('medicine_description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Препарат',
                'verbose_name_plural': 'Препараты',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100, verbose_name='Имя пациента')),
                ('patient_information', models.TextField(verbose_name='Данные пациента')),
                ('medical_Card', models.TextField(verbose_name='Медицинская карта')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='имя автора')),
                ('comment_text', models.CharField(max_length=500, verbose_name='текст комментария')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctor')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
